name: Dockerimage beta

on:
  push:
    branches:
      - master
      - beta

jobs:
  CPU:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
      with:
        branch: beta
    - name: Build the Docker image
      env:
        HUB_NAME: ${{ secrets.DOCKER_NAME }}
        HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
      run: |  
        docker login -u $HUB_NAME -p $HUB_KEY
        docker build . --pull --no-cache --file Dockerfile --tag zocker160/blender-crowdrender:beta
        docker push zocker160/blender-crowdrender:beta


  nvidia:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
      with:
        branch: beta
    - name: Build the Docker image
      env:
        HUB_NAME: ${{ secrets.DOCKER_NAME }}
        HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
      run: |  
        docker login -u $HUB_NAME -p $HUB_KEY
        docker build . --pull --no-cache --file Dockerfile.cuda10 --tag zocker160/blender-crowdrender:nvidia-beta
        docker push zocker160/blender-crowdrender:nvidia-beta
